- path: lib/io/event/priority_heap.rb
  time: 2021-02-12T12:19:44+01:00
  author:
    name: Wander Hillen
    email: wjw.hillen@gmail.com

- path: lib/io/event/priority_heap.rb
  time: 2021-02-12T13:19:56+01:00
  author:
    name: Wander Hillen
    email: wjw.hillen@gmail.com

- path: lib/io/event/priority_heap.rb
  time: 2021-02-12T13:28:58+01:00
  author:
    name: Wander Hillen
    email: wjw.hillen@gmail.com

- path: lib/io/event/priority_heap.rb
  time: 2021-02-13T18:44:46+13:00
  author:
    name: Samuel Williams
    email: samuel.williams@oriontransfer.co.nz

- path: lib/io/event/priority_heap.rb
  time: 2021-02-13T12:40:15+01:00
  author:
    name: Wander Hillen
    email: wjw.hillen@gmail.com

- path: lib/io/event/priority_heap.rb
  time: 2021-02-13T12:47:51+01:00
  author:
    name: Wander Hillen
    email: wjw.hillen@gmail.com

- path: lib/io/event/priority_heap.rb
  time: 2022-09-02T13:45:20+12:00
  author:
    name: Samuel Williams
    email: samuel.williams@oriontransfer.co.nz

- path: lib/io/event/priority_heap.rb
  time: 2022-09-02T13:45:20+12:00
  author:
    name: Samuel Williams
    email: samuel.williams@oriontransfer.co.nz

- path: lib/io/event/priority_heap.rb
  time: 2022-10-13T11:06:34+13:00
  author:
    name: Samuel Williams
    email: samuel.williams@oriontransfer.co.nz

- path: lib/io/event/priority_heap.rb
  time: 2023-04-12T17:25:59+12:00
  author:
    name: Samuel Williams
    email: samuel.williams@oriontransfer.co.nz
