name: Test

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        
        ruby:
          - "3.2"
          - "3.2.6"
          - "3.3"
          - "3.4"
          - "head"
        
        experimental: [false]
        
        include:
          - os: ubuntu
            ruby: truffleruby
            experimental: true
          - os: ubuntu
            ruby: truffleruby-head
            experimental: true
          - os: ubuntu
            ruby: jruby
            experimental: true
          - os: ubuntu
            ruby: head
            experimental: true
    
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Install packages (Ubuntu)
      if: matrix.os == 'ubuntu'
      run: sudo apt-get install -y liburing-dev
    
    - name: Build extensions
      timeout-minutes: 10
      run: bundle exec bake build
    
    - name: Run tests
      timeout-minutes: 10
      run: bundle exec sus --verbose
