name: Test Futex

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6

    - name: Install liburing with futex support
      run: |
        git clone --branch liburing-2.6 --depth 1 https://github.com/axboe/liburing.git /tmp/liburing
        make -C /tmp/liburing -j2
        sudo make -C /tmp/liburing install
        echo "/usr/lib" | sudo tee /etc/ld.so.conf.d/liburing.conf
        sudo ldconfig

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true

    - name: Run futex tests
      timeout-minutes: 5
      env:
        RUBYLIB: lib:ext
      run: |
        cd ext
        bundle exec ruby extconf.rb
        make
        cd ..
        bundle exec ruby -e 'require "io/event"; abort "IO::Event::Futex is unavailable!" unless defined?(IO::Event::Futex)'
        bundle exec sus test/io/event/futex.rb
